server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///ssm?serverTimezone=UTC
    username: root
    password: root
  application:
    name: service-provider # 应用名称，注册到eureka后的服务名称
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka